# Generated by Django 6.1 on 2026-09-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_otp_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='administrativearea',
            unique_together={('name', 'area_type')},
        ),
    ]
