# Generated by Django 6.1 on 2026-09-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_administrativearea_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responderprofile',
            name='administrative_area',
        ),
        migrations.AddField(
            model_name='responderprofile',
            name='administrative_areas',
            field=models.ManyToManyField(blank=True, related_name='responders', to='users.administrativearea'),
        ),
    ]
