# Generated by Django 6.1 on 2026-09-04 07:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('content_bn', models.TextField(blank=True, null=True)),
                ('alert_type', models.CharField(choices=[('cyclone', 'Cyclone Warning'), ('storm_surge', 'Storm Surge Warning'), ('flood', 'Flood Warning'), ('erosion', 'Erosion Warning'), ('general', 'General Alert'), ('emergency', 'Emergency Alert'), ('preparedness', 'Preparedness Instruction'), ('evacuation', 'Evacuation Order')], default='general', max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('affected_districts', models.JSONField(blank=True, default=list)),
                ('affected_upazilas', models.JSONField(blank=True, default=list)),
                ('geofence', models.JSONField(blank=True, default=dict)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('contact_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('report_submission', 'Report Submission'), ('report_update', 'Report Update'), ('alert', 'New Alert'), ('critical_alert', 'Critical Alert'), ('assignment', 'Incident Assignment'), ('reminder', 'Reminder'), ('broadcast', 'Broadcast')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('body_bn', models.TextField(blank=True, null=True)),
                ('channels', models.JSONField(default=list, help_text='email, sms, push, in-app')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='alert_notifications.alert')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='incidents.incidentreport')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'severity'], name='alerts_alert_t_cb4af9_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['valid_from', 'valid_until'], name='alerts_valid_f_d15891_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_active', 'published_at'], name='alerts_is_acti_c4d25e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_b93376_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', 'notification_type'], name='notificatio_status_b03cdb_idx'),
        ),
    ]
