# Generated by Django 6.1 on 2026-09-04 07:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_remove_responderprofile_administrative_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_bn', models.CharField(blank=True, help_text='Bengali name', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_bn', models.TextField(blank=True, help_text='Bengali description', null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50, null=True)),
                ('color_code', models.CharField(default='#FF0000', help_text='Hex color code', max_length=7)),
                ('default_priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incident_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_bn', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=10, null=True)),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], default=3)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('location_source', models.CharField(choices=[('gps', 'GPS'), ('manual', 'Manual Selection'), ('network', 'Network Based')], default='manual', max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('union', models.CharField(blank=True, max_length=100, null=True)),
                ('upazila', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('report_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident_time', models.DateTimeField(blank=True, null=True)),
                ('affected_people_estimate', models.PositiveIntegerField(blank=True, null=True)),
                ('affected_families_estimate', models.PositiveIntegerField(blank=True, null=True)),
                ('injuries_count', models.PositiveIntegerField(default=0)),
                ('fatalities_count', models.PositiveIntegerField(default=0)),
                ('property_damage_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated damage in BDT', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_sos', models.BooleanField(default=False, help_text='Emergency help request')),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.incidentcategory')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_reports', to='incidents.incidentreport')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_incidents', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='incident_attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'avi', 'mp3', 'wav', 'pdf', 'doc', 'docx'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0, editable=False, help_text='File size in bytes')),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], default='photo', max_length=10)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='incident_thumbnails/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('description_bn', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incidents.incidentreport')),
            ],
            options={
                'db_table': 'evidence_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='users.responderprofile')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='incidents.incidentreport')),
            ],
            options={
                'ordering': ['-assignment_time'],
            },
        ),
        migrations.CreateModel(
            name='ResponseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('arrived', 'Arrived at Scene'), ('assessment', 'Assessment'), ('rescue', 'Rescue'), ('evacuation', 'Evacuation'), ('medical', 'Medical Assistance'), ('supply', 'Supply Delivery'), ('communication', 'Communication'), ('resolution', 'Incident Resolved'), ('escalation', 'Incident Escalated'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('description_bn', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('resources_used', models.JSONField(blank=True, default=list)),
                ('personnel_count', models.PositiveIntegerField(default=0)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_actions', to='users.responderprofile')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='incidents.responseassignment')),
            ],
            options={
                'db_table': 'response_actions',
                'ordering': ['-action_time'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('unverified', 'Unverified'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], default='pending', max_length=20)),
                ('priority_assigned', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True)),
                ('severity_assigned', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('comments_bn', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('affected_people_count', models.PositiveIntegerField(blank=True, null=True)),
                ('affected_families_count', models.PositiveIntegerField(blank=True, null=True)),
                ('injuries_count', models.PositiveIntegerField(default=0)),
                ('fatalities_count', models.PositiveIntegerField(default=0)),
                ('response_recommendation', models.TextField(blank=True, null=True)),
                ('recommended_response_team', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_automated', models.BooleanField(default=False)),
                ('automation_confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='incidents.incidentreport')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_records',
                'ordering': ['-verification_time'],
            },
        ),
        migrations.CreateModel(
            name='TriageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_before', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True)),
                ('priority_after', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True)),
                ('triage_notes', models.TextField()),
                ('triage_notes_bn', models.TextField(blank=True, null=True)),
                ('triage_rating', models.PositiveSmallIntegerField(choices=[(1, 'Low urgency'), (2, 'Medium urgency'), (3, 'High urgency'), (4, 'Critical urgency')], default=1)),
                ('factors_considered', models.JSONField(blank=True, default=list)),
                ('estimated_response_time', models.DurationField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triage_logs', to='incidents.incidentcategory')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triage_actions', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_logs', to='incidents.verificationrecord')),
            ],
            options={
                'db_table': 'triage_logs',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['status', 'priority'], name='incident_re_status_6e3098_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['latitude', 'longitude'], name='incident_re_latitud_0fc2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['district', 'upazila', 'union'], name='incident_re_distric_3929f6_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['category', 'is_sos'], name='incident_re_categor_5c55fb_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['created_at'], name='incident_re_created_c2fe61_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrecord',
            index=models.Index(fields=['status', 'incident'], name='verificatio_status_9c9709_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrecord',
            index=models.Index(fields=['verifier', 'verification_time'], name='verificatio_verifie_d3b87a_idx'),
        ),
    ]
