# Generated by Django 6.1 on 2026-09-05 08:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import incidents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('users', '0009_pendingregistration_user_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='responseassignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='verificationrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='incidentreport',
            name='incident_re_distric_3929f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='verificationrecord',
            name='verificatio_status_9c9709_idx',
        ),
        migrations.RemoveIndex(
            model_name='verificationrecord',
            name='verificatio_verifie_d3b87a_idx',
        ),
        migrations.RenameIndex(
            model_name='incidentreport',
            new_name='incidents_i_status_9a8b94_idx',
            old_name='incident_re_status_6e3098_idx',
        ),
        migrations.RenameIndex(
            model_name='incidentreport',
            new_name='incidents_i_latitud_8ce671_idx',
            old_name='incident_re_latitud_0fc2d3_idx',
        ),
        migrations.RenameIndex(
            model_name='incidentreport',
            new_name='incidents_i_categor_5de2ea_idx',
            old_name='incident_re_categor_5c55fb_idx',
        ),
        migrations.RenameIndex(
            model_name='incidentreport',
            new_name='incidents_i_created_e00552_idx',
            old_name='incident_re_created_c2fe61_idx',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='situation',
            field=models.CharField(choices=[('worsening', 'Worsening'), ('stable', 'Stable'), ('improving', 'Improving')], db_index=True, default='stable', max_length=20),
        ),
        migrations.AlterField(
            model_name='evidenceattachment',
            name='file',
            field=models.FileField(upload_to=incidents.models.evidence_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'avi', 'mp3', 'wav', 'pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='evidenceattachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='evidenceattachment',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evidenceattachment',
            name='file_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=20),
        ),
        migrations.AlterField(
            model_name='evidenceattachment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='incidents.incidentreport'),
        ),
        migrations.AlterField(
            model_name='evidenceattachment',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evidenceattachment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='evidenceattachment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='evidenceattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='evidenceattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evidenceattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentcategory',
            name='color_code',
            field=models.CharField(blank=True, help_text='Optional UI color code such as #FF5733.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcategory',
            name='default_priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentcategory',
            name='description_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name or icon identifier used by frontend.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidentcategory',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='affected_families_estimate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='affected_people_estimate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='district',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='division',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='is_sos',
            field=models.BooleanField(db_index=True, default=False, help_text='True when urgent rescue is requested.'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_incident_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters.', null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='location_source',
            field=models.CharField(choices=[('gps', 'GPS'), ('manual', 'Manual'), ('network', 'Network')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='property_damage_estimate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated property damage in BDT.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='report_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='severity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Severity score from 1 (lowest) to 5 (highest).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='union',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='upazila',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='village',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='responseaction',
            name='action_type',
            field=models.CharField(choices=[('arrived', 'Arrived at Location'), ('assessment', 'Assessment'), ('rescue', 'Rescue'), ('evacuation', 'Evacuation'), ('medical', 'Medical Assistance'), ('supply', 'Supply Distribution'), ('communication', 'Communication'), ('resolution', 'Resolution'), ('escalation', 'Escalation'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='responseaction',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_actions', to='incidents.responseassignment'),
        ),
        migrations.AlterField(
            model_name='responseaction',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='responseaction',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='responseaction',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='responseaction',
            name='personnel_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='responseassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_response_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='responseassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_assignments', to='users.responderprofile'),
        ),
        migrations.AlterField(
            model_name='responseassignment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_assignments', to='incidents.incidentreport'),
        ),
        migrations.AlterField(
            model_name='responseassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='triagelog',
            name='category_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_logs', to='incidents.incidentcategory'),
        ),
        migrations.AlterField(
            model_name='triagelog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='triagelog',
            name='priority_after',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triagelog',
            name='priority_before',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='triagelog',
            name='triage_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triagelog',
            name='triage_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'High'), (4, 'Very High')]),
        ),
        migrations.AlterField(
            model_name='verificationrecord',
            name='fatalities_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrecord',
            name='injuries_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrecord',
            name='priority_assigned',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrecord',
            name='severity_assigned',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='verificationrecord',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='evidenceattachment',
            index=models.Index(fields=['incident', 'file_type'], name='incidents_e_inciden_01526d_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceattachment',
            index=models.Index(fields=['uploaded_at'], name='incidents_e_uploade_e53f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='responseaction',
            index=models.Index(fields=['assignment', 'action_time'], name='incidents_r_assignm_902561_idx'),
        ),
        migrations.AddIndex(
            model_name='responseaction',
            index=models.Index(fields=['performed_by', 'action_time'], name='incidents_r_perform_c8099a_idx'),
        ),
        migrations.AddIndex(
            model_name='responseassignment',
            index=models.Index(fields=['incident', 'status'], name='incidents_r_inciden_e78b60_idx'),
        ),
        migrations.AddIndex(
            model_name='responseassignment',
            index=models.Index(fields=['assigned_to', 'status'], name='incidents_r_assigne_a37048_idx'),
        ),
        migrations.AddIndex(
            model_name='triagelog',
            index=models.Index(fields=['verification', 'performed_at'], name='incidents_t_verific_8fc223_idx'),
        ),
        migrations.AddIndex(
            model_name='triagelog',
            index=models.Index(fields=['priority_after'], name='incidents_t_priorit_572c43_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrecord',
            index=models.Index(fields=['incident', 'status'], name='incidents_v_inciden_1bf2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrecord',
            index=models.Index(fields=['verifier'], name='incidents_v_verifie_c30ca1_idx'),
        ),
        migrations.AlterModelTable(
            name='evidenceattachment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='incidentcategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='incidentreport',
            table=None,
        ),
        migrations.AlterModelTable(
            name='responseaction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='triagelog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='verificationrecord',
            table=None,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='damage_types',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='incidents.damagetype'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['district', 'upazila'], name='incidents_i_distric_f5152f_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['situation'], name='incidents_i_situati_f763f8_idx'),
        ),
    ]
