# Generated by Django 6.1 on 2026-09-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_damagetype_alter_responseassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
