# Generated by Django 6.1 on 2026-09-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_shelter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelter',
            options={'ordering': ['district', 'upazila', 'name']},
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='description',
        ),
        migrations.AddField(
            model_name='shelter',
            name='constructed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='construction_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='facilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shelter',
            name='power',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelter',
            name='water',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CROWDED', 'Crowded'), ('FULL', 'Full'), ('READY', 'Ready'), ('MAINTENANCE', 'Maintenance')], default='READY', max_length=20),
        ),
    ]
