# Generated by Django 6.1.1 on 2026-09-27 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_alter_shelter_options_remove_shelter_description_and_more'),
        ('users', '0009_pendingregistration_user_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='responseassignment',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_assignments', to='users.communityvolunteerprofile'),
        ),
        migrations.AlterField(
            model_name='responseassignment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_assignments', to='users.responderprofile'),
        ),
        migrations.AddIndex(
            model_name='responseassignment',
            index=models.Index(fields=['assigned_volunteer', 'status'], name='incidents_r_assigne_c75b36_idx'),
        ),
        migrations.AddConstraint(
            model_name='responseassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_to__isnull', False), ('assigned_volunteer__isnull', True)), models.Q(('assigned_to__isnull', True), ('assigned_volunteer__isnull', False)), _connector='OR'), name='response_assignment_one_assignee'),
        ),
    ]
